allowBuilds:
  "@clerk/shared": false
  "@prisma/client": false
  "@prisma/engines": false
  bufferutil: false
  core-js: false
  prisma: false
  sharp: false
  unrs-resolver: false
  utf-8-validate: false
