allowBuilds:
  "@clerk/shared": false
  "@prisma/client": false
  "@prisma/engines": false
  bufferutil: set this to true or false
  core-js: set this to true or false
  prisma: false
  sharp: false
  unrs-resolver: false
  utf-8-validate: set this to true or false
