export type CldUploadWidgetInfo = {
  access_mode: "public" | "authenticated";
  api_key: string;
  asset_id: string;
  batchId: string;
  bytes: number;
  context: Record<string, Record<string, string>>;
  created_at: string;
  etag: string;
  folder: string;
  format: string;
  height: number;
  hook_execution: Record<string, unknown>;
  id: string;
  info: Record<string, unknown>;
  original_filename: string;
  pages: number;
  path: string;
  placeholder: boolean;
  public_id: string;
  resource_type: "image" | "raw" | "video" | "auto";
  secure_url: string;
  signature: string;
  tags: string[];
  thumbnail_url: string;
  type: "upload" | "private" | "authenticated";
  url: string;
  version: number;
  width: number;
  [key: string]: unknown;
};
